export const headingIconText = {
    aboutUs__IconText: "About Us",
    knowAboutConcretePumping__IconText: "Know About Concrete Pumping",
    workStyle__IconText: "Works Style",
    concretePumpingService__IconText: "Concrete Pumping Service",
    ourPortfolio__IconText: "Our Portfolio",
    exOfOurCompany__IconText: "Experienced Of Our Company",
    leadingCompany__IconText: "Leading Company",
    expertArea__IconText: "Expert Area",
    ourWorkingProcess__IconText: "Our Working Process",
    anySizePr__IconText: "Any Size Projects With Us",
    DepandableConcrete__IconText: "Dependable Concrete Pump Trucks Company",
    map__IconTxt: "Our Service Areas",
    ourServices__IconTxt: "Services",
    whoIsBest__IconText: 'Who Is Best',
    IsConcreteCostly__IconText: "Is Concrete Pumping Costly?",
    faq__IconText: "Frequently Asked Questions (FAQ)",
    meterialNEquip__IconText: "Materials and Equipment",
    benefits__IconText: "About Us",
    review__IconText: "Review",
    hire__IconText: "Hire For Installation Services ",
    joinUs__IconText: "Join With Us",
    Benefits__IconText: "Benefits with Easy Pools",

}